language: node_js

node_js:
  - "10"

sudo: false

before_script:
- if ! [ -x "$(command -v aws)" ]; then curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" ; unzip awscliv2.zip ; sudo ./aws/install ; fi
- aws sts get-caller-identity

before_install:
  - nvm install-latest-npm

addons:
  apt:
    sources: [ 'ubuntu-toolchain-r-test' ]
    packages: [ 'libstdc++-5-dev' ]

env:
  global:
  - secure: uLTEYEfOuF5VidH9fOhOdxly/9ChkAwTKw7DZltmiNfy+QZ5QmDfXIgVj0hJRfeUFPd3+r+WwL68nEFj8fG9SCAAHeYUR9ewEwKkpZ0141zF7PpgftFWuLk64YPYNgd+R4wfdS3I63OSHQWpwOykZEcd3GBVIuHopt9At+KiyB8=
